# Generated by Django 4.2.5 on 2024-02-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="fare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flight", models.CharField(max_length=30)),
                ("flight_class", models.CharField(max_length=30)),
                ("flight_fare", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="flights_from_to",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_from", models.CharField(max_length=30)),
                ("to_to", models.CharField(max_length=30)),
                ("flight", models.CharField(max_length=30)),
                ("date", models.CharField(default="", max_length=30)),
            ],
        ),
    ]
