# Generated by Django 5.0.2 on 2024-02-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_fare_flights_from_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_name', models.CharField(max_length=30)),
                ('flight_class', models.CharField(max_length=30)),
                ('final_fare', models.CharField(max_length=30)),
                ('departure', models.CharField(max_length=30)),
                ('arrival', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('num_of_travellers', models.IntegerField()),
            ],
        ),
    ]
