# Generated by Django 5.0.2 on 2024-02-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_booking_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_history',
            name='time',
        ),
        migrations.AlterField(
            model_name='booking_history',
            name='arrival',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking_history',
            name='departure',
            field=models.CharField(default='', max_length=30),
        ),
    ]
