# Generated by Django 5.0.2 on 2024-02-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_remove_booking_history_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_history',
            name='final_fare',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking_history',
            name='flight_class',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking_history',
            name='flight_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking_history',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking_history',
            name='num_of_travellers',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='flights_from_to',
            name='date',
            field=models.DateField(verbose_name='departure Date'),
        ),
    ]
