# Generated by Django 5.0.2 on 2024-03-05 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_alter_booking_history_final_fare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_history',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='flight.user'),
        ),
    ]
