# Generated by Django 5.0.2 on 2024-03-05 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0006_booking_history_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_history',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.user'),
        ),
    ]
