# Generated by Django 5.0.2 on 2024-03-05 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0007_alter_booking_history_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_history',
            name='username',
        ),
    ]
