# Generated by Django 5.0.2 on 2024-03-05 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0008_remove_booking_history_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_history',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='flight.user'),
            preserve_default=False,
        ),
    ]
