# Generated by Django 5.0.2 on 2024-03-05 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0009_booking_history_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fare',
            name='id',
        ),
        migrations.AddField(
            model_name='fare',
            name='fid',
            field=models.CharField(default='', max_length=30, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flights_from_to',
            name='fid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='flight.user'),
            preserve_default=False,
        ),
    ]
