# Generated by Django 5.0.2 on 2024-03-05 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0010_remove_fare_id_fare_fid_flights_from_to_fid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights_from_to',
            name='fid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.fare'),
        ),
    ]
