# Generated by Django 5.0.2 on 2024-03-05 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0011_alter_flights_from_to_fid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_history',
            name='flight_class',
        ),
        migrations.RemoveField(
            model_name='booking_history',
            name='flight_name',
        ),
        migrations.AddField(
            model_name='booking_history',
            name='fid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='flight.fare'),
            preserve_default=False,
        ),
    ]
